name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build
      run: wasm-pack build --target web --out-name evaluate --out-dir out
      
    - name: Expose Filesystem For Debugging
      run: find .
 
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        clean: true
        clean-exclude: out/evaluate_bg.wasm out/evaluate.js
        single-commit: true
        branch: gh-pages
        folder: out